### ISSUE TITLE
WORM update

### ISSUE THREAD

**Issue by netapp-rlithman** [NetAppDocs/bluexp-cloud-volumes-ontap#203]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html#how-worm-storage-works

### Page title

WORM storage

### Summary

How can customers with node-based licenses activate WORM? It seems to be a problem for these customers.

@netapp-driley Fyi

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ejoschko** [comment]
The problem is that there are different license models PayGo and BYOL.

For PayGo, the documentation is correct, because here when concluding the subscription and specifying that WORM is required, these costs are charged directly.

For customers who use BYOL, the documentation does not work, you know neither how to turn on the WORM functionality nor whether and how to pay for it.

**Comment by netapp-driley** [comment]
Hi Eric - Thank you so much for your feedback. I'll present this item to the CVO team to determine how to best to address this item. I will keep you posted once the updated documentation is available. 

If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
Updated the[ Charging section of the WORM Storage topic](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html#charging).
