### ISSUE TITLE
Keystone as a license type but no cloud marketplaces?

### ISSUE THREAD

**Issue by mgraws** [NetAppDocs/bluexp-cloud-volumes-ontap#231]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

Should we add cloud marketplaces as a CVO licensing option?  To me Keystone is a route to market and procurement method for the capacity based license.  If we list Keystone we should list marketplaces in my opinion.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hello. Thanks for sharing your thoughts. If you're a NetApper, let me know and I can include you in internal comms about this. We'll need to reach out to our team before we can provide feedback on this one.

**Comment by netapp-rlithman** [comment]
I learned the following: 

- Marketplace subscriptions are listed on the Licensing page. They are a “[consumption model](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#consumption-models)” for capacity-based licensing (along with BYOL and annual contracts)

- Keystone is listed separately because that’s how it’s presented to the user: capacity-based licensing is a Cloud Volumes ONTAP licensing model separate from NetApp Keystone

Given this information, do the docs provide what you're looking for? If not, please let us know.

**Comment by netapp-rlithman** [comment]
I'm going to close this issue. Please let us know if you need anything further.
